name: smart_waste_management
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: ^0.11.0
  image_picker: ^1.0.4
  image: ^4.1.3 
  google_generative_ai: ^0.2.0 
  flutter_markdown: ^0.7.6+2
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  sqflite: ^2.4.2
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/waste_classifier_Vgg16_besttflite.tflite


